# Generated by Django 5.2.6 on 2025-10-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_config_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='config',
            new_name='coordinates',
        ),
        migrations.AddField(
            model_name='project',
            name='max_zoom',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='project',
            name='min_zoom',
            field=models.IntegerField(default=10),
        ),
    ]
